name: 'Request package bundle'
description: Request npm package bundled, with minified, .d.ts file.
title: "Request bundle: "
labels: ["request bundle"]
assignees:
  - ducan-ne

body:
  - type: input
    id: packageName
    attributes:
      label: NPM package name
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      value: latest
    validations:
      required: true

  - type: input
    id: external
    attributes:
      label: External that exclude from bundle, separated by comma (for example "pg-native,pg-android")
    validations:
      required: false

  - type: dropdown
    id: engine
    attributes:
      label: Bundler
      description: What the bundler you want to bunlding?
      options:
        - esbuild
        - ncc
    validations:
      required: true

  - type: checkboxes
    id: options
    attributes:
      label: Bundle options
      description: Bundle options
      # Unfortunately, GitHub currently not support value field, so we'll keep the label as the value
      options:
        - label: minify
