export const ORG_NAME = 'clgtIO'
export const REPO_NAME = 'autobundle'
export const REQUEST_BUNDLE_LABEL = 'request bundle'
export const FAILED_TO_RELEASE_LABEL = 'failed to release'
export const BUNDLE_RELEASED_LABEL = 'bundle released'
