name: Request bundle

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  request-bundle:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Autobundle Bot
        uses: ./autobundle-bot
