name: Request bundle

on:
  issues:
    types:
      - opened

jobs:
  request-bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Autobundle Bot
        uses: ../../autobundle-bot
