name: Request bundle

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  request-bundle:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Autobundle Bot
        uses: ./autobundle-bot
        with:
          token: ${{secrets.GH_TOKEN}}
