name: Request bundle

on:
  issues:
    types:
      - labeled

jobs:
  request-bundle:
    if: ${{ github.event.label.name == 'request bundle' }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install --prefer-lock
      - run: yarn --cwd autobundle-bot build
      - name: Autobundle Bot
        uses: ./autobundle-bot
        with:
          token: ${{secrets.GH_TOKEN}}
          npmToken: ${{secrets.NPM_TOKEN}}
